### ISSUE TITLE
No htscodecs repository

### ISSUE THREAD

**Issue by gerbenvoshol** [jkbonfield/fqzcomp5#1]
Hi,

Thanks for making this repository available. Storage is always an issues and I wanted to include your tool an in evaluation with GeneZip, ORA, etc. However, I was unable to build the programs since the htscodecs is missing.

Tried:
```
git clone --recursive https://github.com/jkbonfield/fqzcomp5
```

I also could not build after including your current htscodes repository and it is also missing the thread_pool implementation.

**Comment by jkbonfield** [comment]
Hmm I see what you mean.  Odd!

The repository and branch it's trying to use is this: https://github.com/jkbonfield/htscodecs/tree/fqz_seq_u32
So you could clone that manually.

I'll see if I can figure out what broke with my submodule.  Thanks for the bug report.

**Comment by gerbenvoshol** [comment]
Thanks! I cloned the repository and tried to compile the program again, Unfortunately, I get the following error:

```
fqzcomp5.c:117:10: fatal error: thread_pool.h: No such file or directory
  117 | #include "thread_pool.h"
```

I guess the htslib thread_pool might also be missing

**Comment by jkbonfield** [comment]
Sorry about this.  fqzcomp5 was very much a local work in progress that I ran out of time to tidy up.  I have some half finished indexing too to permit random access, but I see that never got checked in (nor finished).  The format is block based though, unlike the original fqzcomp, with an aim to permitting this and also offering better parallelism.

Anyway, hopefully the issue is now resolved.  I've checked it locally.

Thanks for the bug report.
